import type { Metadata } from "next";
import styles from "./layout.module.scss"
import { MapProvider } from "./components/Map/contexts/MapContext";
import Header from "./components/Header/Header";
import Sidebar from "./components/Sidebar/Sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className={styles.appContainer}>
          
          <div className={styles.mainContent}>
            <MapProvider>
            <Sidebar />
            <div className={styles.contentArea}>
              <Header />
              {children}
            </div>
            </MapProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
