import type { Metadata } from "next";
import styles from "@/layout.module.scss"
import { MapProvider } from "@/components/Map/contexts/MapContext";
import "@/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className={styles.appContainer}>
          <div className={styles.mainContent}>
            <MapProvider>
              <div className={styles.contentArea}>
                {children}
              </div>
            </MapProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
